[2025-10-30 00:42:25,369 : numexpr.utils : INFO : Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-10-30 00:42:25,369 : numexpr.utils : INFO : NumExpr defaulting to 8 threads.]
[2025-10-30 00:42:25,990 : datasciencelogger : INFO : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-30 00:42:25,990 : datasciencelogger : ERROR : [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "d:\mlops\datasciencProject\main.py", line 9, in <module>
    obj.initiate_data_ingestion()
  File "d:\mlops\datasciencProject\src\datasciencProject\pipeline\data_ingestion.py", line 13, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\config\configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CFRBACKUP-WZITMJTO\anaconda3\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 32, in read_yaml
    raise e
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 25, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2025-10-30 00:48:37,367 : numexpr.utils : INFO : Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-10-30 00:48:37,367 : numexpr.utils : INFO : NumExpr defaulting to 8 threads.]
[2025-10-30 00:48:37,891 : datasciencelogger : INFO : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-30 00:48:37,892 : datasciencelogger : ERROR : [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "d:\mlops\datasciencProject\main.py", line 9, in <module>
    obj.initiate_data_ingestion()
  File "d:\mlops\datasciencProject\src\datasciencProject\pipeline\data_ingestion.py", line 13, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\config\configuration.py", line 12, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CFRBACKUP-WZITMJTO\anaconda3\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 32, in read_yaml
    raise e
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 25, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2025-10-30 00:55:18,788 : numexpr.utils : INFO : Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-10-30 00:55:18,789 : numexpr.utils : INFO : NumExpr defaulting to 8 threads.]
[2025-10-30 00:55:19,329 : datasciencelogger : INFO : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-30 00:55:19,330 : datasciencelogger : ERROR : [Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "d:\mlops\datasciencProject\main.py", line 9, in <module>
    obj.initiate_data_ingestion()
  File "d:\mlops\datasciencProject\src\datasciencProject\pipeline\data_ingestion.py", line 13, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\config\configuration.py", line 12, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CFRBACKUP-WZITMJTO\anaconda3\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 32, in read_yaml
    raise e
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 25, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2025-10-30 00:58:09,579 : numexpr.utils : INFO : Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-10-30 00:58:09,580 : numexpr.utils : INFO : NumExpr defaulting to 8 threads.]
[2025-10-30 00:58:10,135 : datasciencelogger : INFO : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-30 00:58:10,135 : datasciencelogger : ERROR : [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "d:\mlops\datasciencProject\main.py", line 9, in <module>
    obj.initiate_data_ingestion()
  File "d:\mlops\datasciencProject\src\datasciencProject\pipeline\data_ingestion.py", line 13, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\config\configuration.py", line 12, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CFRBACKUP-WZITMJTO\anaconda3\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 32, in read_yaml
    raise e
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 25, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2025-10-30 00:58:28,251 : numexpr.utils : INFO : Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-10-30 00:58:28,251 : numexpr.utils : INFO : NumExpr defaulting to 8 threads.]
[2025-10-30 00:58:28,724 : datasciencelogger : INFO : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-30 00:58:28,740 : datasciencelogger : ERROR : [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "d:\mlops\datasciencProject\main.py", line 9, in <module>
    obj.initiate_data_ingestion()
  File "d:\mlops\datasciencProject\src\datasciencProject\pipeline\data_ingestion.py", line 13, in initiate_data_ingestion
    config=ConfigurationManager()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\config\configuration.py", line 12, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CFRBACKUP-WZITMJTO\anaconda3\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 32, in read_yaml
    raise e
  File "d:\mlops\datasciencProject\src\datasciencProject\utils\common.py", line 25, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
